### PR TITLE
WIP: New Notification System 

### PR DESCRIPTION
**Pull request by stacmi**
# This is a WIP - Do Not Merge - this code is not in working condition yet

## purpose

This pull request is for collaboration on the new system which is not yet finished

### notes

new endpoints for notifications consistiong of 

- POST
- PATCH
- GET

Currently there is only skeleton code for **POST** which still needs a lot of work

### CODE REVIEW

**Comment by stephenermshar** [comment]
A few of thoughts for this:
* take a look at other endpoints to see how post and get requests are handled. Typically one endpoint is used for interacting with one resource, the difference between GET and POST is in in the headers of a request rather than the URL.
* a good way to get started is to clean out the methods for post and get that are associated with your new endpoint and try to get them to just return something like a `'helloworld'` to the client. the `self.status` and `self.write` methods are used for sending a response to the client.
* once you get a successful response we can focus on interacting with the database and securing the endpoint.

**Comment by octagonprogramming** [comment]
reconfigured endpoints per what we talked about but forgot to commit them before switching back to windows os

**Comment by octagonprogramming** [comment]
moved the notifications code into homepage and then started creating the notifications db

**Comment by octagonprogramming** [comment]
@stephenermshar 

There is an issue setting the current user of the session. Issue appears when adding the decorator `@tornado.web.authenticated` where the issue of `current_user has no attribute username` come up. Need to look into it more as currently using postman requests to test the new changes.

Core functionality works. Working on adding authentication and validators.

**Comment by stephenermshar** [comment]
what's in your `settings.py` file?

**Comment by octagonprogramming** [comment]
```
keys = {
    'hmac':"fakekeystring",
    'samlEndpointKey': "fakekeystring"
}
testing = {
    'pytest': False,  # enables access to roles endpoint, set to false in production
    'dev': True,  # bypasses authentication and logs in `developer`
    'developer': 2024971,
    'base_url': 'http://127.0.0.1',
    'port': 8888,
    'log_name': 'aswwu_test',
    'current_year': '1920',
    'database': './testing_databases',
}
production = {
    'port': 8888,
    'log_name': 'aswwu',
    'current_year': '1920',
}
email = {
    'username': 'aswwu.webmaster@wallawalla.edu',
    'password': 'fakepassword'
}
database = {
    'location': './testing_databases'
}
```

**Comment by stephenermshar** [comment]
This could be related to the `database['location']` variable being set to `'./testing_databases'` rather than your actual local database. the `poeople.db` `'./testing_databases'` probably doesn't contain your wwuid. There's a new `settings.py` file I'm working on that should address that issue.  Until then, make sure you have a copy of the full database in a folder on the same level as your python repository, and set
```
database = {
    'location': './testing_databases'
}
```

**Comment by octagonprogramming** [comment]
Code is up to date.

Core functionality tested and working using postman requests.

secured the endpoint for post/put requests.

**Comment by stephenermshar** [comment]
quick reminder: make sure you make the notification_links column name singular.

**Comment by stephenermshar** [comment]
To make sure this project is in a good state when the school year ends, I think it would be good to prepare it for deployment and have it running on the live server early this week. Until the frontend administration components are finished we'll have to add and remove notifications with SQL through SSH, which is still an improvement over redeploying the frontend site with html notifications.

this week make sure:
- [ ] you know how to migrate the database to the new schema, and
- [x] the API can return a list of all notifications stored in the table.

**Pull request closed without merging**
